apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
    serving.knative.dev/creator: system:admin
    serving.knative.dev/lastModifier: system:admin
  labels:
    boson.dev/function: "true"
    boson.dev/runtime: go
    function.knative.dev: "true"
    function.knative.dev/name: process-function
    function.knative.dev/runtime: go
  name: process-function
spec:
  template:
    metadata:
      labels:
        
        function.knative.dev: "true"
        function.knative.dev/name: process-function
        function.knative.dev/runtime: go
    spec:
      containerConcurrency: 0
      containers:
      - env:
        - name: BUILT
          value: 20221022T171652
        {{ if .Values.teamName }}
        - name: INPUT_SOURCE_URL
          value: http://input-source-x-default-x-{{ .Values.teamName }}.{{ .Values.teamName }}.{{ .Values.domainName }}
        {{ end }}
        image: docker.io/salaboy/process-function@sha256:7016611a7e85632ea177672e07d42f6be4b420e0fcf66d54188ab3b26f099264
        livenessProbe:
          httpGet:
            path: /health/liveness
            port: 0
        name: user-container
        readinessProbe:
          httpGet:
            path: /health/readiness
            port: 0
          successThreshold: 1
        resources: {}
      enableServiceLinks: false
      timeoutSeconds: 300
  traffic:
  - latestRevision: true
    percent: 100
