apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
    serving.knative.dev/creator: system:admin
    serving.knative.dev/lastModifier: system:admin
  labels:
    boson.dev/function: "true"
    boson.dev/runtime: go
    function.knative.dev: "true"
    function.knative.dev/name: process-function
    function.knative.dev/runtime: go
  name: process-function
spec:
  template:
    metadata:
      labels:
        
        function.knative.dev: "true"
        function.knative.dev/name: process-function
        function.knative.dev/runtime: go
    spec:
      containerConcurrency: 0
      containers:
      - env:
        - name: BUILT
          value: 20221022T171652
        image: docker.io/salaboy/process-function@sha256:7261f1b032778acfae20fc786914ca1bf4d83de097b8145f151a8af666afcfe4
        livenessProbe:
          httpGet:
            path: /health/liveness
            port: 0
        name: user-container
        readinessProbe:
          httpGet:
            path: /health/readiness
            port: 0
          successThreshold: 1
        resources: {}
      enableServiceLinks: false
      timeoutSeconds: 300
  traffic:
  - latestRevision: true
    percent: 100
